export  const CREATE_COUPON_REQUEST = "CREATE_COUPON_REQUEST"
export const CREATE_COUPON_SUCCESS = "CREATE_COUPON_SUCCESS"
export const CREATE_COUPON_FAIL = "CREATE_COUPON_FAIL"

export const GET_ALL_COUPON_REQUEST = "GET_ALL_COUPON_REQUEST"
export const GET_ALL_COUPON_SUCCESS = "GET_ALL_COUPON_SUCCESS"
export const GET_ALL_COUPON_FAIL = "GET_ALL_COUPON_FAIL"