// Get all categories
export const GET_ALL_CATEGORIES_REQUEST = "GET_ALL_CATEGORIES_REQUEST";
export const GET_ALL_CATEGORIES_SUCCESS = "GET_ALL_CATEGORIES_SUCCESS";
export const GET_ALL_CATEGORIES_FAILURE = "GET_ALL_CATEGORIES_FAILURE";

// Get category hierarchy
export const GET_CATEGORY_HIERARCHY_REQUEST = "GET_CATEGORY_HIERARCHY_REQUEST";
export const GET_CATEGORY_HIERARCHY_SUCCESS = "GET_CATEGORY_HIERARCHY_SUCCESS";
export const GET_CATEGORY_HIERARCHY_FAILURE = "GET_CATEGORY_HIERARCHY_FAILURE";

// Get categories by level
export const GET_CATEGORIES_BY_LEVEL_REQUEST = "GET_CATEGORIES_BY_LEVEL_REQUEST";
export const GET_CATEGORIES_BY_LEVEL_SUCCESS = "GET_CATEGORIES_BY_LEVEL_SUCCESS";
export const GET_CATEGORIES_BY_LEVEL_FAILURE = "GET_CATEGORIES_BY_LEVEL_FAILURE";

// Get child categories
export const GET_CHILD_CATEGORIES_REQUEST = "GET_CHILD_CATEGORIES_REQUEST";
export const GET_CHILD_CATEGORIES_SUCCESS = "GET_CHILD_CATEGORIES_SUCCESS";
export const GET_CHILD_CATEGORIES_FAILURE = "GET_CHILD_CATEGORIES_FAILURE";

// Create category
export const CREATE_CATEGORY_REQUEST = "CREATE_CATEGORY_REQUEST";
export const CREATE_CATEGORY_SUCCESS = "CREATE_CATEGORY_SUCCESS";
export const CREATE_CATEGORY_FAILURE = "CREATE_CATEGORY_FAILURE";

// Update category
export const UPDATE_CATEGORY_REQUEST = "UPDATE_CATEGORY_REQUEST";
export const UPDATE_CATEGORY_SUCCESS = "UPDATE_CATEGORY_SUCCESS";
export const UPDATE_CATEGORY_FAILURE = "UPDATE_CATEGORY_FAILURE";

// Delete category
export const DELETE_CATEGORY_REQUEST = "DELETE_CATEGORY_REQUEST";
export const DELETE_CATEGORY_SUCCESS = "DELETE_CATEGORY_SUCCESS";
export const DELETE_CATEGORY_FAILURE = "DELETE_CATEGORY_FAILURE";
